kzk/urls.py
# -*- coding: utf-8 -*-


"""kzk URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.10/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^', include('projekty.urls')),
    url(r'^admin/', include('smuggler.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^projekty/', include('projekty.urls')),
    url(r'^konta/', include('registration.backends.simple.urls')),
    url(r'^admin/', admin.site.urls),
#    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]

projekty/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from . import views
from .models import Nazwa
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView

from django.contrib import admin
from django.conf import settings


from django.views.generic import DeleteView, DetailView

app_name = 'projekty'

urlpatterns = [url(r'^$', views.index, name='index'),
               url(r'^lista/', login_required(ListView.as_view(model=Nazwa)),
               name='lista'),
               url(r'^dodaj/$', views.NazwaCreate.as_view(), name='dodaj'),
               url(r'^edytuj/(?P<pk>\d+)/', views.NazwaUpdate.as_view(), name='edytuj'),
               url(r'^usun/(?P<pk>\d+)/', views.NazwaDelete.as_view(), name='usun'),
               #url(r'^info/(?P<pk>\d+)/', views.NazwaDetail.as_view(), name='info'),
              
]

handler404 = 'projekty.views.custom_404'

handler500 = 'projekty.views.custom_500'

projekty/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location='/media/photos')


# Create your models here.

@python_2_unicode_compatible
class Nazwa(models.Model):
    nazwa_projektu = models.CharField(max_length=50)
    #data_publikacji = models.DateTimeField('data publikacji', null=False)
    autor = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)
    krotki_opis = models.CharField(max_length=200)
    dlugi_opis = models.CharField(max_length=500)
    problemy = models.CharField(max_length=500)
    bledy = models.CharField(max_length=500)
    szkola = models.CharField(max_length=200)
    liczba_uczniow = models.IntegerField(default=0)
    informacje = models.CharField(max_length=200)

    
    def __str__(self):
        return self.nazwa_projektu
        
    class Meta:
        verbose_name_plural = 'nazwy'
    
#class Photo(models.Model):
#    docfile = models.FileField(upload_to='documents/%Y/%m/%d')   

    
"""
@python_2_unicode_compatible
class Dane(models.Model):
    nazwa = models.ForeignKey(Nazwa, on_delete=models.CASCADE)
    opis_projektu = models.CharField(max_length=200)
    szkola = models.CharField(max_length=200)
    liczba_uczniow = models.IntegerField(default=0)
    
    def __str__(self):
        return self.opis_projektu

    class Meta:
        verbose_name_plural = 'dane'
"""

projekty/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, Textarea
from . import models
from django.forms.models import inlineformset_factory
from django import forms

class NazwaForm(ModelForm):
    
    class Meta:
        model = models.Nazwa
        exclude = ('data_publikacji', '#')
        zdjecie = forms.FileField(label='Select a file')
        widgets = {'nazwa_projektu': Textarea(attrs={'rows':1, 'cols': 75}),
                   'krotki_opis': Textarea(attrs={'rows':1, 'cols': 75}),
                   'dlugi_opis': Textarea(attrs={'rows':1, 'cols': 75}),
                   'problemy': Textarea(attrs={'rows':1, 'cols': 75}),
                   'bledy': Textarea(attrs={'rows':1, 'cols': 75}),
                   'szkola': Textarea(attrs={'rows':1, 'cols':50}),
                   'liczba_uczniow': Textarea(attrs={'rows':1, 'cols': 75}),
				   'informacje': Textarea(attrs={'rows':2, 'cols':50}),
    
                    }

class PhotoForm(forms.Form):
    docfile = forms.FileField(
        label = 'Wybierz plik',
        help_text='tekst pomocniczy',
        )            
        
"""
DaneFormSet = inlineformset_factory(
    parent_model=models.Nazwa,
    model=models.Dane,
    validate_max=True,
    validate_min=True,
    max_num=10,
    min_num=1,
    fields=('nazwa', 'opis_projektu', 'szkola', 'liczba_uczniow')
    
)
"""

projekty/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from . import models
from . import forms
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse


def index(request):
    kontekst = {'komunikat': "Witamy w aplikacji Projekty KzK! Tu możesz założyć konto, zalogować się i zgłosić swój projekt. Zapraszamy!"}
    return TemplateResponse(request, 'projekty/index.html', kontekst)

def custom_404(request):
    return render(request, '404.html', {}, status=404)

def custom_500(request):
    return render(request, '500.html', {}, status=500)

@method_decorator(login_required, 'dispatch')
class NazwaCreate(CreateView):
    """Widok dodawania projektów"""
    
    model = models.Nazwa
    form_class = forms.NazwaForm
    success_url = reverse_lazy('projekty:lista')
    
    def nazwa(request):
        if request.method == 'POST':
            form = PhotoForm(request.POST, request.FILES)
            if form.is_valid():
                newdoc = Photo(docfile=reques.FILES['docfile'])
                newdoc.save()
                
                return HttpResponseRedirect(reverse('list'))
        else:
            form = PhotoForm()
            
        documents = Photo.objects.all()
        
        return render(
            request,
            'nazwa.html',
            {'documents': documents, 'form': form}
        )


@method_decorator(login_required, 'dispatch')
class NazwaUpdate(UpdateView):
    """Widok aktualizuacji"""

    model = models.Nazwa
    form_class = forms.NazwaForm
    success_url = reverse_lazy('projekty:lista')
    
@method_decorator(login_required, 'dispatch')
class NazwaDelete(DeleteView):
    model = models.Nazwa
    success_url = reverse_lazy('projekty:lista')
    

    
    
#DetailView na później ++++
    
"""
@method_decorator(login_required, 'dispatch')
class NazwaDetailView(DetailView):
    model = models.Nazwa
    
"""





"""
    def get_context_data(self, **kwargs):
        context = super(NazwaDelete, self).get_context_data(**kwargs)
        info = models.Nazwa.objects.filter(projekty=self.object)
        context['info'] = info
        return context
""" 


"""
    
    def get_context_data(self, **kwargs):
        context = super(NazwaCreate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['dane'] = forms.DaneFormSet(self.request.POST)
        else:
            context['dane'] = forms.DaneFormSet()
        return context

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        dane = forms.DaneFormSet(self.request.POST)
        if form.is_valid() and dane.is_valid():
            return self.form_valid(form, dane)
        else:
            return self.form_invalid(form, dane)

    def form_valid(self, form, dane):
        form.instance.autor = self.request.user
        self.object = form.save()
        dane.instance = self.object
        dame.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, dane):
        return self.render_to_response(
            self.get_context_data(form=form, dane=dane)
        )
    


"""

projekty/templates/projekty/base.html
{% load static %}<!DOCTYPE html>
<html lang="pl">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block tytul_head %} Projekty Koduj z Klasą{% endblock %}</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link href="{% static 'projekty/css/projekty.css' %}" rel="stylesheet">
</head>
<body>

<!-- Nawigacja -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Przełącz nawigację</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'projekty:index' %}">
        <img src="{% static 'projekty/images/kodujzklasa_m.jpg' %}" class="img-thumbnail">
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {% if not user.is_authenticated %}
        <li><a href="{% url 'auth_login' %}">Zaloguj</a></li>
        <li><a href="{% url 'registration_register' %}">Utwórz konto</a></li>
        {% else %}
        <li><a href="{% url 'projekty:dodaj' %}">Dodaj projekt</a></li>
        <li><a href="{% url 'projekty:lista' %}">Lista projektów</a></li>
        <li><a href="{% url 'auth_logout' %}">Wyloguj</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<!-- Treść główna -->
<div class="container">

  <div class="row">

    <div class="col-sm-8">

      <noscript><p>Uaktywnij bsługę JavaScript.</p></noscript>

      <!-- blok tytułu strony -->
      <h1>{% block tytul_h1 %}{% endblock %}</h1>

      <!-- blok treści -->
      <div class="tresc">
        {% block tresc %}{% endblock %}
      </div>

    </div>

    <div class="col-sm-3 col-sm-offset-1">
      <div class="well">
        <h4>Przydatne linki</h4>
        <ul>
          {% block linki_ul %}{% endblock %}
        </ul>
      </div> <!--/well-->
    </div>

  </div> <!--/row -->
</div> <!--/container -->

<div class="container footer">
  <footer>
    <div class="row">
      <div class="col-sm-12 text-center">
        <div class="well">Projekty Django Koduj z Klasą - kurs i prezentacja<br>&copy; by Koduj z klasą 2017</div>
      </div>
    </div>
  </footer>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</body>
</html>

projekty/templates/projekty/index.html
{% extends "projekty/base.html" %}

{% block tytul_h1 %}

Projekty KZK - zapraszamy do rejestracji!

{% endblock %}

{% block tresc %}
   <p> {{ komunikat }}</p>

{% endblock %}

{% block linki_ul %}
  <li><a href="http://django-maly-bar.rtfd.io">Dokumentacja aplikacji</a></li>
  <li><a href="https://www.djangoproject.com/">Django – web framework</a></li>
  <li><a href="http://django.pl/">Polska strona Django</a></li>
  <li><a href="http://getbootstrap.com/">Bootstrap</a></li>
  <li><a href="http://www.w3schools.com/bootstrap/">Bootstrap Tutorial</a></li>
  <li><a href="https://www.python.org/">Python</a></li>
  <li><a href="http://python101.readthedocs.io/">Materiały Python 101</a></li>
{% endblock %}

projekty/templates/projekty/nazwa_confirm_delete.html
<h1>Usuwanie projektu</h1>
<form action="." method="post">
  {% csrf_token %}
  <p>Czy na pewno chcesz usunąć projekt?:<br />"{{ object }}"?</p>
  <button type="submit">Usuń</button>
</form>

projekty/templates/projekty/nazwa_form.html
<h1>Dodaj projekt</h1>

<form action="." method="post" id="pform">
  {% csrf_token %}
  {{ form.as_p }}

  <h3>Dane:</h3>
  {{ dane.management_form }}
  {{ dane.non_form_errors }}
  {% for d in dane %}
  {{ d.id }}
    <div class="{{ dane.prefix }}">
      <span>{{ forloop.counter }})&nbsp;</span>
      {{ d.dane.errors }}
      {{ d.opis_projektu.errors }}
      {{ d.nazwa.label_tag }} {{ d.nazwa }}
      {{ d.opis_projektu.label_tag }} {{ d.opis_projektu }}
    </div>
  {% endfor %}
  <br /><input type="submit" value="Zapisz">
</form>

projekty/templates/projekty/nazwa_list.html
<h1>Lista projektów</h1>

<table class="table">
<tr><th>Lp.</th><th>Nazwa</th><th>Szkoła</th><th>Operacje</th></tr>

{% for p in object_list %}

<tr>
  <td>{{ forloop.counter }}</td>
  <td>{{ p.nazwa_projektu }}</td>
  <td>{{ p.szkola}}</td>
  <td>
    {% if p.autor.username == user.username %}
      <a href="{% url 'projekty:edytuj' p.id %}">Edytuj</a> &bull;
      <a href="{% url 'projekty:usun' p.id %}">Usuń</a>
    {% endif %}
  </td>
</tr>
{% endfor %}
</table>